<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Install</AssemblyName>
    <RootNamespace>K50BridgeSetup</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>x86</Platforms>
    <PlatformTarget>x86</PlatformTarget>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
  </PropertyGroup>

</Project>
